[project]
name = "coord-ds"
version = "0.1.0"
description = ""
authors = [{ name = "whatphilipcodes", email = "gerdes.philip@gmail.com" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = "^3.11"
dependencies = [
    "datasets (>=3.4.0,<4.0.0)",
    "sentence-transformers (>=3.4.1,<4.0.0)",
    "umap-learn (>=0.5.7,<0.6.0)",
    "scikit-learn (>=1.6.1,<2.0.0)",
    "numpy (>=1.0.0,<2.0.0)",
    "numba (>=0.61.0,<0.62.0)",
    "matplotlib (>=3.10.6,<4.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "einops (>=0.8.1,<0.9.0)",
    "tqdm (>=4.67.1,<5.0.0)",
    "torch (>=2.8.0,<3.0.0)",
    "opentsne (>=1.0.2,<2.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
torch = { url = "https://download.pytorch.org/whl/cu128/torch-2.8.0%2Bcu128-cp311-cp311-win_amd64.whl" }

[tool.poetry.group.dev.dependencies]
jupyter = "^1.1.1"
